import "./components/fixedHeader";
import "./components/blockAnimation";
import "./components/burgerMenu"
import "./components/modal"
import "./components/lazyLoadin"
import "./components/phoneMask"
import "./components/contact-form"
import "./components/sendFormData"
import "./components/formValidation"
import "./components/swiper"